version: "3"

x-redis-env: &redis-env
  REDIS_HOST: "redis"
  REDIS_PORT: 6379

x-grpc-env: &grpc-env
  PROVIDER_CONNS: "provider-stocks:9000=TCSG,YNDX,SBER,TSLA,MOEX;provider-crypto:9092=BTC-USD,ETH-USD,XRM-USD,BTC-RUB,ETH-RUB,XRM-RUB;provider-dummy:50000=dummy"

services:
  redis:
    image: docker.io/library/redis:6.2

  worker:
    image: docker.io/mkls0/prediction-service:0.1
    build:
      dockerfile: ./Dockerfile
    command: "/app/worker.py"
    entrypoint: "python"
    environment:
      <<: *redis-env
    depends_on:
    - redis

  scheduler:
    image: docker.io/mkls0/prediction-service:0.1
    build:
      dockerfile: ./Dockerfile
    entrypoint: "python"
    command: "/app/scheduler.py"
    ports:
    - "5000:5000"
    environment:
      <<: *redis-env
      <<: *grpc-env
    depends_on:
    - provider-dummy
    - redis

  provider-crypto:
    image: docker.io/korpatiy/finance-dashboard-provider-crypto:v0.2.0-dev
    environment:
      CRYPTO_KEY: ***REMOVED***
      CRYPTO_URI: https://api.coinbase.com/v2
      CRYPTO_DELAY: 10000
      CRYPTO_GRPC_PORT: 9092
      CRYPTO_PORT: 9091
    ports:
      - "9091:9091"
      - "9092:9092"

  provider-dummy:
    image: docker.io/mkls0/dummy-grpc-provider:0.1

